### ISSUE TITLE
R.<X> = Zmod(n)[] ? 

### ISSUE THREAD

**Issue by Scalpel78** [deut-erium/WriteUps#1]
Hi, very nice writeups!
I have a question about the "We are related" writeup. In the sagescript you use
`R.<X> = Zmod(n)[]`
What does the `<X>` part mean? 
I'm having issues running and understanding the sage script, so it would be great if you could say a few words about how it works.

**Comment by deut-erium** [comment]
I am sorry that I didnt clarify,
<X> part means univariate in X,
R.<X> = Zmod(n)[]

Means R is a univariate polynomial Ring in X over ring of integers n

I am relatively new to sage too, I need to figure out to do things python
way, sympy could be an option which I can explore
Suggest a better way to ask doubts, i feel someone else also might need to
reach out.
Cheers
